// app/components/component/NormCard.tsx
import { Clock, TrendingUp, User as UserIcon } from "lucide-react"
import { Link } from "react-router"

import { Card } from "~/components/ui/card"
import { translateGrade } from "~/lib/utils"

function ProgressBar({
  current,
  max,
  className,
}: {
  current: number
  max: number
  className?: string
}) {
  const percentage = Math.min(100, Math.max(0, (current / max) * 100))

  let colorClass = "bg-blue-600 dark:bg-blue-500"
  if (percentage >= 100) colorClass = "bg-emerald-500 dark:bg-emerald-400"
  else if (percentage < 50) colorClass = "bg-red-500 dark:bg-red-600"
  else if (percentage < 80) colorClass = "bg-amber-500 dark:bg-amber-600"

  return (
    <div
      className={`h-2 w-full overflow-hidden rounded-full bg-slate-200 dark:bg-slate-700 ${className}`}
    >
      <div
        className={`h-2 rounded-full transition-all duration-500 ease-out ${colorClass}`}
        style={{ width: `${percentage}%` }}
      />
    </div>
  )
}

interface NormCardUser {
  id: string
  imageUrl: string
  lastName: string | null
  firstName: string | null
}

interface NormCardProps {
  user: NormCardUser
  norm:
    | {
        userId: string
        current: number
        required: number
        grade: number
        lastPromotionDate: string | null
      }
    | undefined
  progress: number
}

export function NormCard({ user, norm, progress }: NormCardProps) {
  return (
    <Link to={`/admin/user/${user.id}`} className="group block">
      <Card
        className={`h-full overflow-hidden transition-all duration-300 hover:-translate-y-0.5 hover:shadow-lg`}
      >
        <div className="space-y-4 p-3">
          <div className="mb-3 flex items-start justify-between">
            <div className="flex items-center gap-3">
              <div className="flex h-10 w-10 items-center justify-center overflow-hidden rounded-full bg-slate-100 text-lg font-bold text-slate-600 dark:bg-slate-800 dark:text-slate-300">
                {user.imageUrl ? (
                  <img
                    src={user.imageUrl}
                    alt=""
                    className="h-full w-full object-cover"
                  />
                ) : (
                  <UserIcon className="h-5 w-5" />
                )}
              </div>
              <div>
                <h3 className="font-bold text-slate-900 transition-colors group-hover:text-blue-600 dark:text-slate-100 dark:group-hover:text-blue-400">
                  {user.lastName} {user.firstName}
                </h3>
                <p className="mt-0.5 font-mono text-xs text-slate-500 dark:text-slate-400">
                  {norm?.grade !== undefined && norm?.grade !== null
                    ? translateGrade(norm.grade)
                    : "未設定"}
                </p>
              </div>
            </div>
            <div className="flex flex-col place-items-end">
              <div className="mt-0.5 flex flex-row items-center gap-1 text-slate-500 dark:text-slate-400">
                <Clock className="h-3 w-3" />
                <span className="text-xs">
                  {norm?.lastPromotionDate
                    ? new Date(norm.lastPromotionDate).toLocaleDateString("ja-JP")
                    : "記録なし"}
                </span>
              </div>
            </div>
          </div>

          <div className="space-y-2">
            <div className="flex justify-between text-xs">
              <div className="flex items-center gap-1">
                <span className="flex items-center gap-1 text-slate-500 dark:text-slate-400">
                  <TrendingUp className="h-3 w-3" />
                </span>
                <span className="font-mono font-bold text-slate-900 dark:text-slate-100">
                  {Math.round(progress)}%
                </span>
              </div>
              <span>
                {Math.floor(norm?.current || 0)} / {norm?.required || 0} 回
              </span>
            </div>
            <ProgressBar current={norm?.current || 0} max={norm?.required || 1} />
          </div>
        </div>
      </Card>
    </Link>
  )
}

// src/components/admin/NormCard.vue
<template>
  <div
    class="bg-white dark:bg-neutral-800 rounded-xl shadow-sm border border-neutral-200 dark:border-neutral-800 p-4 md:p-6 flex flex-col gap-4"
    data-testid="norm-card">
    <div class="flex items-start justify-between gap-3">
      <div class="flex items-center gap-3">
        <img :src="user.imageUrl" alt="" class="w-10 h-10 rounded-full bg-neutral-200" />
        <div>
          <div class="font-medium text-neutral-900 dark:text-neutral-100">{{ user.lastName }} {{ user.firstName }}</div>
          <div class="text-xs text-neutral-500 flex flex-wrap gap-x-2">
            <span>{{ norm.gradeLabel }}</span>
            <span v-if="norm.lastPromotionDate" class="text-neutral-400">•</span>
            <span v-if="norm.lastPromotionDate">昇級: {{ norm.lastPromotionDate }}</span>
          </div>
        </div>
      </div>
      <div class="shrink-0">
        <span
          :class="[
            'px-2 py-0.5 text-xs font-medium rounded-full',
            progress >= 100
              ? 'bg-emerald-100 text-emerald-700 dark:bg-emerald-900/30 dark:text-emerald-400'
              : 'bg-amber-100 text-amber-700 dark:bg-amber-900/30 dark:text-amber-400',
          ]"
          data-testid="norm-status">
          {{ progress >= 100 ? "達成" : "未達成" }}
        </span>
      </div>
    </div>

    <div class="flex-1 flex flex-col justify-end gap-2">
      <!-- Progress Bar -->
      <div class="space-y-1">
        <div class="flex justify-between text-xs text-neutral-500">
          <span>進捗率 {{ Math.min(100, Math.round(progress)) }}%</span>
          <span class="font-medium text-neutral-700 dark:text-neutral-300">
            {{ norm.current }} / {{ norm.required }} 回
          </span>
        </div>
        <div class="h-1.5 w-full bg-neutral-100 dark:bg-neutral-700 rounded-full overflow-hidden">
          <div
            class="h-full bg-indigo-600 rounded-full transition-all duration-500"
            :style="{ width: `${Math.min(100, progress)}%` }"
            data-testid="norm-progress"></div>
        </div>
      </div>
    </div>
  </div>
</template>

<script setup lang="ts">
import type { AdminUserType } from "@/share/types/admin"

interface NormData {
  userId: string
  current: number
  required: number
  progress: number
  isMet: boolean
  grade: number
  gradeLabel: string
  lastPromotionDate: string | null
}

defineProps<{ user: AdminUserType; norm: NormData; progress: number }>()
</script>
