// app/routes/admin/norms.tsx
import type { User } from "@clerk/react-router/server"
import { ArrowDown01, ArrowUp01, Search } from "lucide-react"
import { useMemo } from "react"
import type { LoaderFunctionArgs, MetaFunction } from "react-router"
import { useSearchParams } from "react-router"

import type { Route } from "./+types/norms"

import { NormCard } from "~/components/component/NormCard"
import { Input } from "~/components/ui/input"
import { ac } from "~/lib/api-client"

// MARK: Constants
const MAX_SEARCH_LENGTH = 100
const PERCENTAGE_MULTIPLIER = 100

// MARK: Types
type UserNorm = {
  userId: string
  current: number
  required: number
  grade: number
  lastPromotionDate: string | null
}

// MARK: Helper Functions
function sortByProgress<T extends { progress: number; isMet: boolean }>(
  a: T,
  b: T,
  order: "asc" | "desc",
): number {
  if (order === "asc") {
    // Ascending: unmet first (worst progress first), then met
    if (a.isMet !== b.isMet) return a.isMet ? 1 : -1
    return a.progress - b.progress
  } else {
    // Descending: met first (best progress first), then unmet
    if (a.isMet !== b.isMet) return a.isMet ? -1 : 1
    return b.progress - a.progress
  }
}

// MARK: Loader
export async function loader(args: LoaderFunctionArgs) {
  const { request } = args
  const url = new URL(request.url)
  const rawSearch = url.searchParams.get("search") || ""
  const search = rawSearch.trim().slice(0, MAX_SEARCH_LENGTH)

  try {
    const client = ac({ request })
    const response = await client.norms.$get({ query: { query: search } })

    if (!response.ok) {
      throw new Error("Failed to fetch norms")
    }

    const data = await response.json()
    return { users: data.users as User[], search: data.search, norms: data.norms }
  } catch {
    return { users: [] as User[], search, norms: [] as UserNorm[] }
  }
}

// MARK: Meta
export const meta: MetaFunction = () => {
  return [
    { title: "稽古日数 - ハム大合気ポータル" },
    {
      name: "description",
      content: "部員の昇級・昇段審査に向けた稽古ノルマの進捗状況を確認します。",
    },
  ]
}

// MARK: Main Component
export default function NormsPage(args: Route.ComponentProps) {
  const { users, norms } = args.loaderData
  const [searchParams, setSearchParams] = useSearchParams()

  const searchTerm = searchParams.get("search") || ""
  const filterStatus = (searchParams.get("filter") as "all" | "met" | "unmet") || "all"
  const sortOrder = (searchParams.get("sort") as "asc" | "desc") || "desc"

  const updateSearchParams = (updates: Record<string, string>) => {
    setSearchParams(prev => {
      const newParams = new URLSearchParams(prev)
      Object.entries(updates).forEach(([key, value]) => {
        if (value) {
          newParams.set(key, value)
        } else {
          newParams.delete(key)
        }
      })
      return newParams
    })
  }

  const filteredUsers = useMemo(() => {
    return users
      .map(user => {
        const userNorm = norms.find(n => n.userId === user.id)
        const current = userNorm?.current || 0
        const required = userNorm?.required || 1
        const progress = (current / required) * PERCENTAGE_MULTIPLIER
        const isMet = current >= required

        return { user, norm: userNorm, progress, isMet }
      })
      .filter(({ user, isMet }) => {
        const searchLower = searchTerm.toLowerCase()
        const fullName = `${user.lastName || ""} ${user.firstName || ""}`.toLowerCase()
        const matchesSearch = fullName.includes(searchLower)

        const matchesStatus =
          filterStatus === "all" ||
          (filterStatus === "met" && isMet) ||
          (filterStatus === "unmet" && !isMet)

        return matchesSearch && matchesStatus
      })
      .sort((a, b) => sortByProgress(a, b, sortOrder))
  }, [users, norms, searchTerm, filterStatus, sortOrder])

  return (
    <div className="mx-auto max-w-7xl space-y-8 p-4 md:p-8">
      <div className="flex flex-col items-center justify-between gap-4 sm:flex-row">
        <div className="relative w-full sm:w-72">
          <Search className="absolute top-1/2 left-3 h-4 w-4 -translate-y-1/2 text-slate-400" />
          <Input
            placeholder="名前で検索..."
            value={searchTerm}
            onChange={e => updateSearchParams({ search: e.target.value })}
            className="border-slate-200 bg-white pl-9 dark:border-slate-800 dark:bg-slate-950"
          />
        </div>

        <div className="flex w-full items-center gap-4 sm:w-auto">
          <div className="flex rounded-lg bg-slate-200 p-1 dark:bg-slate-800">
            <button
              onClick={() => updateSearchParams({ sort: "asc" })}
              className={`rounded-md p-1.5 transition-all ${
                sortOrder === "asc"
                  ? "bg-white text-slate-900 shadow-sm dark:bg-slate-950 dark:text-slate-50"
                  : "text-slate-600 hover:text-slate-900 dark:text-slate-400 dark:hover:text-slate-200"
              }`}
              title="進捗率が低い順"
            >
              <ArrowUp01 className="h-4 w-4" />
            </button>
            <button
              onClick={() => updateSearchParams({ sort: "desc" })}
              className={`rounded-md p-1.5 transition-all ${
                sortOrder === "desc"
                  ? "bg-white text-slate-900 shadow-sm dark:bg-slate-950 dark:text-slate-50"
                  : "text-slate-600 hover:text-slate-900 dark:text-slate-400 dark:hover:text-slate-200"
              }`}
              title="進捗率が高い順（達成優先）"
            >
              <ArrowDown01 className="h-4 w-4" />
            </button>
          </div>

          <div className="flex items-center gap-2">
            <div className="flex rounded-lg bg-slate-200 p-1 dark:bg-slate-800">
              <button
                onClick={() => updateSearchParams({ filter: "all" })}
                className={`rounded-md px-3 py-1.5 text-sm font-medium transition-all ${
                  filterStatus === "all"
                    ? "bg-white text-slate-900 shadow-sm dark:bg-slate-950 dark:text-slate-50"
                    : "text-slate-600 hover:text-slate-900 dark:text-slate-400 dark:hover:text-slate-200"
                }`}
              >
                全て
              </button>
              <button
                onClick={() => updateSearchParams({ filter: "unmet" })}
                className={`rounded-md px-3 py-1.5 text-sm font-medium transition-all ${
                  filterStatus === "unmet"
                    ? "bg-white text-red-600 shadow-sm dark:bg-slate-950 dark:text-red-400"
                    : "text-slate-600 hover:text-slate-900 dark:text-slate-400 dark:hover:text-slate-200"
                }`}
              >
                未達成
              </button>
              <button
                onClick={() => updateSearchParams({ filter: "met" })}
                className={`rounded-md px-3 py-1.5 text-sm font-medium transition-all ${
                  filterStatus === "met"
                    ? "bg-white text-emerald-600 shadow-sm dark:bg-slate-950 dark:text-emerald-400"
                    : "text-slate-600 hover:text-slate-900 dark:text-slate-400 dark:hover:text-slate-200"
                }`}
              >
                達成済
              </button>
            </div>
          </div>
        </div>
      </div>

      <div className="grid grid-cols-1 gap-6 md:grid-cols-2">
        {filteredUsers.map(({ user, norm, progress }) => (
          <NormCard key={user.id} user={user} norm={norm} progress={progress} />
        ))}
      </div>

      {filteredUsers.length === 0 && (
        <div className="py-12 text-center text-slate-500 dark:text-slate-400">
          <p>該当するユーザーが見つかりません</p>
        </div>
      )}
    </div>
  )
}

// src/views/admin/Norms.vue
<template>
  <div class="space-y-4 md:space-y-6 px-3 md:px-6">
    <AdminMenu />
    <div class="flex flex-col sm:flex-row justify-between items-start sm:items-center gap-4">
      <!-- Filter & Sort Controls -->
      <div class="flex flex-wrap items-center gap-4 w-full sm:w-auto">
        <!-- Status Filter -->
        <div class="flex bg-neutral-100 dark:bg-neutral-800 rounded-lg p-1">
          <button
            @click="filterStatus = 'all'"
            :class="[
              'px-3 py-1.5 text-sm font-medium rounded-md transition-all',
              filterStatus === 'all'
                ? 'bg-white dark:bg-neutral-700 shadow-sm text-neutral-900 dark:text-neutral-100'
                : 'text-neutral-500 hover:text-neutral-900 dark:hover:text-neutral-300',
            ]">
            全て
          </button>
          <button
            @click="filterStatus = 'unmet'"
            :class="[
              'px-3 py-1.5 text-sm font-medium rounded-md transition-all',
              filterStatus === 'unmet'
                ? 'bg-white dark:bg-neutral-700 shadow-sm text-red-600 dark:text-red-400'
                : 'text-neutral-500 hover:text-neutral-900 dark:hover:text-neutral-300',
            ]">
            未達成
          </button>
          <button
            @click="filterStatus = 'met'"
            :class="[
              'px-3 py-1.5 text-sm font-medium rounded-md transition-all',
              filterStatus === 'met'
                ? 'bg-white dark:bg-neutral-700 shadow-sm text-emerald-600 dark:text-emerald-400'
                : 'text-neutral-500 hover:text-neutral-900 dark:hover:text-neutral-300',
            ]">
            達成済
          </button>
        </div>

        <!-- Sort Order -->
        <div class="flex bg-neutral-100 dark:bg-neutral-800 rounded-lg p-1">
          <button
            @click="sortOrder = 'asc'"
            title="進捗率: 低→高"
            :class="[
              'px-3 py-1.5 text-sm font-medium rounded-md transition-all',
              sortOrder === 'asc'
                ? 'bg-white dark:bg-neutral-700 shadow-sm text-neutral-900 dark:text-neutral-100'
                : 'text-neutral-500 hover:text-neutral-900 dark:hover:text-neutral-300',
            ]">
            昇順
          </button>
          <button
            @click="sortOrder = 'desc'"
            title="進捗率: 高→低"
            :class="[
              'px-3 py-1.5 text-sm font-medium rounded-md transition-all',
              sortOrder === 'desc'
                ? 'bg-white dark:bg-neutral-700 shadow-sm text-neutral-900 dark:text-neutral-100'
                : 'text-neutral-500 hover:text-neutral-900 dark:hover:text-neutral-300',
            ]">
            降順
          </button>
        </div>
      </div>
    </div>

    <!-- Search Bar -->
    <div class="relative w-full sm:w-72">
      <input
        v-model="searchTerm"
        type="text"
        placeholder="名前で検索..."
        class="w-full px-3 py-2 pl-9 bg-white dark:bg-neutral-800 border border-neutral-300 dark:border-neutral-800 rounded-md shadow-sm focus:outline-none focus:ring-2 focus:ring-indigo-500" />
    </div>

    <div v-if="loading" class="flex justify-center py-12">
      <Loading />
    </div>

    <div v-else-if="error" class="p-4 bg-red-50 text-red-700 rounded-md border border-red-200">
      {{ error }}
    </div>

    <div v-else class="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6">
      <NormCard
        v-for="item in filteredUsers"
        :key="item.user.id"
        :user="item.user"
        :norm="item.norm"
        :progress="item.norm.progress" />
    </div>

    <div v-if="!loading && !error && filteredUsers.length === 0" class="text-center py-12 text-neutral-500">
      該当するユーザーが見つかりません
    </div>
  </div>
</template>

<script setup lang="ts">
import { ref, computed } from "vue"
import { useQuery } from "@tanstack/vue-query"
import { queryKeys } from "@/src/lib/queryKeys"
import hc from "@/src/lib/honoClient"
import Loading from "@/src/components/ui/Loading.vue"
import NormCard from "@/src/components/admin/NormCard.vue"
import AdminMenu from "@/src/components/admin/AdminMenu.vue"


const searchTerm = ref("")
const filterStatus = ref<"all" | "met" | "unmet">("all")
const sortOrder = ref<"asc" | "desc">("desc")

const {
  data,
  isLoading: loading,
  error: queryError,
} = useQuery({
  queryKey: computed(() => queryKeys.admin.norms({ query: { query: searchTerm.value, limit: 100 } })),
  queryFn: async () => {
    const res = await hc.admin.norms.$get({
      query: { query: searchTerm.value, limit: 100 },
    })
    if (!res.ok) throw new Error("Failed to fetch norms")
    return res.json()
  },
})

const users = computed(() => {
  if (!data.value || !('users' in data.value)) return []
  return data.value.users
})

const norms = computed(() => {
  if (!data.value || !('norms' in data.value)) return []
  return data.value.norms
})

const error = computed(() => (queryError.value ? "データの取得に失敗しました" : ""))

// Reactivity handled by queryKey
// const fetchNorms = ... removed

const processedData = computed(() => {
  return users.value
    .map(user => {
      const norm = norms.value.find(n => n.userId === user.id)
      if (!norm) return null
      return { user, norm }
    })
    .filter((item): item is NonNullable<typeof item> => item !== null)
})

const filteredUsers = computed(() => {
  let result = processedData.value

  // Filter by Search Term
  if (searchTerm.value) {
    const term = searchTerm.value.toLowerCase()
    result = result.filter(item => {
      const fullName =
        `${item.user.lastName || ""} ${item.user.firstName || ""}`.toLowerCase()
      return fullName.includes(term)
    })
  }

  // Filter by Status
  if (filterStatus.value !== "all") {
    result = result.filter(item => {
      if (filterStatus.value === "met") return item.norm.isMet
      if (filterStatus.value === "unmet") return !item.norm.isMet
      return true
    })
  }

  // Sort
  result.sort((a, b) => {
    const diff = a.norm.progress - b.norm.progress
    return sortOrder.value === "asc" ? diff : -diff
  })

  return result
})
</script>
