// src/components/signup/ProgressIndicator.vue
<template>
  <div class="flex justify-center items-center my-4" data-testid="progress-indicator">
    <div
      :class="[
        'text-sm p-2',
        step === 'basic'
          ? 'text-blue-600 dark:text-blue-400 font-semibold'
          : 'text-green-600 dark:text-green-400',
      ]"
      data-testid="step-basic">
      基本情報
    </div>
    <div class="flex-auto border-t-2 transition duration-500 ease-in-out border-gray-300 dark:border-neutral-700"></div>
    <div
      :class="[
        'text-sm p-2',
        step === 'personal'
          ? 'text-blue-600 dark:text-blue-400 font-semibold'
          : step === 'profile'
            ? 'text-green-600 dark:text-green-400'
            : 'text-gray-500 dark:text-neutral-500',
      ]"
      data-testid="step-personal">
      個人情報
    </div>
    <div class="flex-auto border-t-2 transition duration-500 ease-in-out border-gray-300 dark:border-neutral-700"></div>
    <div
      :class="[
        'text-sm p-2',
        step === 'profile'
          ? 'text-blue-600 dark:text-blue-400 font-semibold'
          : 'text-gray-500 dark:text-neutral-500',
      ]"
      data-testid="step-profile">
      プロフィール
    </div>
  </div>
</template>

<script setup lang="ts">
type SignUpStep = "basic" | "personal" | "profile"

defineProps<{ step: SignUpStep }>()
</script>

// app/components/component/sign-up/ProgressIndicator.tsx
import { tv } from "tailwind-variants"

export const ProgressIndicator = ({
  step,
}: {
  step: "basic" | "personal" | "profile"
}) => {
  const steps = ["基本情報", "個人情報", "プロファイル"]
  const currentIndex =
    step === "basic" ? 0 : step === "personal" ? 1 : step === "profile" ? 2 : 2

  const indicator = tv({
    base: "w-6 h-6 rounded-full flex items-center justify-center text-xs font-bold",
    variants: {
      step: {
        current: "bg-blue-600 text-white",
        completed: "border-2 border-green-600 text-green-600",
        upcoming: "bg-slate-200 text-slate-500 dark:bg-slate-600 dark:text-slate-200",
      },
    },
  })

  return (
    <div className="mb-6 flex justify-center">
      {steps.map((label, idx) => (
        <div key={label} className="flex items-center">
          <div
            className={indicator({
              step:
                idx < currentIndex
                  ? "completed"
                  : idx === currentIndex
                    ? "current"
                    : "upcoming",
            })}
          >
            {idx + 1}
          </div>
          {idx < steps.length - 1 && (
            <div className="w-6 h-0.5 bg-slate-400 dark:bg-slate-500 mx-2" />
          )}
        </div>
      ))}
    </div>
  )
}
