// src/components/signup/SignUpStepProfile.vue
<template>
  <div class="space-y-4">
    <div class="grid grid-cols-2 gap-4">
      <div class="space-y-2">
        <label for="year" class="text-sm font-medium text-neutral-700 dark:text-neutral-300">学年</label>
        <select
          id="year"
          :value="formValues.year"
          @change="onUpdate('year', ($event.target as HTMLSelectElement).value)"
          :disabled="isSignUpCreated"
          class="w-full rounded-md border border-neutral-300 dark:border-neutral-700 bg-white dark:bg-neutral-900 px-3 py-2 text-sm text-neutral-900 dark:text-neutral-100 focus:outline-none focus:ring-2 focus:ring-indigo-500 disabled:opacity-50 disabled:cursor-not-allowed">
          <option v-for="y in yearOptions" :key="y.year" :value="y.year">
            {{ y.name }}
          </option>
        </select>
        <p v-if="formErrors.year" class="text-sm text-red-600 dark:text-red-400">
          {{ formErrors.year }}
        </p>
      </div>
      <div class="space-y-2">
        <label for="grade" class="text-sm font-medium text-neutral-700 dark:text-neutral-300">級段位</label>
        <select
          id="grade"
          :value="formValues.grade"
          @change="
            onUpdate(
              'grade',
              Number(($event.target as HTMLSelectElement).value)
            )
          "
          :disabled="isSignUpCreated"
          class="w-full rounded-md border border-neutral-300 dark:border-neutral-700 bg-white dark:bg-neutral-900 px-3 py-2 text-sm text-neutral-900 dark:text-neutral-100 focus:outline-none focus:ring-2 focus:ring-indigo-500 disabled:opacity-50 disabled:cursor-not-allowed">
          <option v-for="g in gradeOptions" :key="g.grade" :value="g.grade">
            {{ g.name }}
          </option>
        </select>
        <p v-if="formErrors.grade" class="text-sm text-red-600 dark:text-red-400">
          {{ formErrors.grade }}
        </p>
      </div>
    </div>

    <div class="space-y-2">
      <label for="joinedAt" class="text-sm font-medium text-neutral-700 dark:text-neutral-300">入部年度</label>
      <input
        id="joinedAt"
        type="number"
        :value="formValues.joinedAt"
        @input="
          onUpdate(
            'joinedAt',
            Number(($event.target as HTMLInputElement).value)
          )
        "
        :disabled="isSignUpCreated"
        class="w-full rounded-md border border-neutral-300 dark:border-neutral-700 bg-white dark:bg-neutral-900 px-3 py-2 text-sm text-neutral-900 dark:text-neutral-100 focus:outline-none focus:ring-2 focus:ring-indigo-500 disabled:opacity-50 disabled:cursor-not-allowed" />
      <p v-if="formErrors.joinedAt" class="text-sm text-red-600 dark:text-red-400">
        {{ formErrors.joinedAt }}
      </p>
    </div>

    <div class="space-y-2">
      <label for="getGradeAt" class="text-sm font-medium text-neutral-700 dark:text-neutral-300"
        >取得年月日 (任意)</label
      >
      <input
        id="getGradeAt"
        type="date"
        :value="formValues.getGradeAt"
        @input="
          onUpdate('getGradeAt', ($event.target as HTMLInputElement).value)
        "
        :disabled="isSignUpCreated"
        class="w-full rounded-md border border-neutral-300 dark:border-neutral-700 bg-white dark:bg-neutral-900 px-3 py-2 text-sm text-neutral-900 dark:text-neutral-100 focus:outline-none focus:ring-2 focus:ring-indigo-500 disabled:opacity-50 disabled:cursor-not-allowed" />
      <p v-if="formErrors.getGradeAt" class="text-sm text-red-600 dark:text-red-400">
        {{ formErrors.getGradeAt }}
      </p>
    </div>

    <div class="flex items-center space-x-2">
      <input
        id="legalAccepted"
        type="checkbox"
        :checked="formValues.legalAccepted"
        @change="
          onUpdate('legalAccepted', ($event.target as HTMLInputElement).checked)
        "
        :disabled="isSignUpCreated"
        class="h-4 w-4 rounded border-neutral-300 text-indigo-600 focus:ring-indigo-600 dark:border-neutral-700 dark:bg-neutral-900" />
      <label for="legalAccepted" class="text-sm text-neutral-700 dark:text-neutral-300">
        利用規約とプライバシーポリシーに同意します。
      </label>
    </div>
    <p v-if="formErrors.legalAccepted" class="text-sm text-red-600 dark:text-red-400">
      {{ formErrors.legalAccepted }}
    </p>

    <div class="flex justify-between pt-2">
      <button
        type="button"
        @click="prevStep"
        :disabled="isSignUpCreated"
        class="rounded-md border border-neutral-300 dark:border-neutral-600 px-4 py-2 text-sm font-medium text-neutral-700 dark:text-neutral-300 hover:bg-neutral-50 dark:hover:bg-neutral-800 focus:outline-none focus:ring-2 focus:ring-indigo-500 disabled:opacity-50 disabled:cursor-not-allowed">
        戻る
      </button>
      <button
        type="submit"
        :disabled="!canSubmit"
        class="rounded-md bg-indigo-600 px-4 py-2 text-sm font-medium text-white hover:bg-indigo-700 focus:outline-none focus:ring-2 focus:ring-indigo-500 disabled:opacity-50 disabled:cursor-not-allowed">
        {{ isSignUpCreated ? "登録中..." : "登録" }}
      </button>
    </div>
  </div>
</template>

<script setup lang="ts">
import { year as yearOptions } from "@/share/lib/year"
import { grade as gradeOptions } from "@/share/lib/grade"
import type { SignUpFormData, FormErrors } from "@/src/composable/useSignUpForm"

const props = defineProps<{
  formValues: Partial<SignUpFormData>
  formErrors: Partial<FormErrors>
  isSignUpCreated: boolean
  canSubmit: boolean
  prevStep: () => void
}>()

const emit = defineEmits<{
  (e: "update:formValue", key: keyof SignUpFormData, value: any): void
}>()

const onUpdate = (key: keyof SignUpFormData, value: any) => {
  emit("update:formValue", key, value)
}
</script>

// app/components/component/sign-up/SignUpStepProfile.tsx
import type { FetcherWithComponents } from "react-router"
import { Link } from "react-router"

import { Button } from "~/components/ui/button"
import { Checkbox } from "~/components/ui/checkbox"
import { DatePicker } from "~/components/ui/date-picker"
import { Input } from "~/components/ui/input"
import { Label } from "~/components/ui/label"
import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from "~/components/ui/select"
import type { ClientActionReturn, FormAction, LocalFormState } from "~/hooks/useSignUpForm"
import { JoinedAtYearRange, grade, year } from "~/lib/utils"
import { style } from "~/styles/component"

type SignUpStepProfileProps = {
  formValues: LocalFormState
  formErrors: Record<string, string>
  dispatch: React.Dispatch<FormAction>
  fetcher: FetcherWithComponents<ClientActionReturn>
  isSignUpCreated: boolean
  prevStep: () => void
  canSubmit: boolean
}

// 学年・級の選択肢生成
function yearOptions() {
  return year.map(y => (
    <SelectItem key={y.year} value={y.year}>
      {y.name}
    </SelectItem>
  ))
}

function gradeOptions() {
  return grade.map(g => (
    <SelectItem key={g.grade} value={String(g.grade)}>
      {g.name}
    </SelectItem>
  ))
}

export function SignUpStepProfile({
  formValues,
  formErrors,
  dispatch,
  fetcher,
  isSignUpCreated,
  prevStep,
  canSubmit,
}: SignUpStepProfileProps) {
  return (
    <div className="space-y-4">
      <h2 className="text-lg font-semibold">プロファイル情報</h2>
      <div className="space-y-2">
        <Label htmlFor="year" className={style.label.required()}>
          学年
        </Label>
        <Select
          name="year"
          required
          value={formValues.year}
          onValueChange={value =>
            dispatch({ type: "SET_FORM_VALUES", payload: { year: value } })
          }
        >
          <SelectTrigger id="year">
            <SelectValue placeholder="学年を選択" />
          </SelectTrigger>
          <SelectContent>{yearOptions()}</SelectContent>
        </Select>
        {formErrors.year && (
          <p className="text-sm font-medium text-destructive">{formErrors.year}</p>
        )}
      </div>
      <div className="space-y-2">
        <Label htmlFor="grade" className={style.label.required()}>
          現在の級段位
        </Label>
        <Select
          name="grade"
          required
          value={String(formValues.grade)}
          onValueChange={value =>
            dispatch({ type: "SET_FORM_VALUES", payload: { grade: Number(value) } })
          }
        >
          <SelectTrigger id="grade">
            <SelectValue placeholder="級段位を選択" />
          </SelectTrigger>
          <SelectContent>{gradeOptions()}</SelectContent>
        </Select>
        {formErrors.grade && (
          <p className="text-sm font-medium text-destructive">{formErrors.grade}</p>
        )}
      </div>
      <div className="space-y-2">
        <Label htmlFor="joinedAt" className={style.label.required()}>
          入部年度
        </Label>
        <Input
          id="joinedAt"
          name="joinedAt"
          type="number"
          required
          min={JoinedAtYearRange.min}
          max={JoinedAtYearRange.max}
          value={formValues.joinedAt}
          onChange={e =>
            dispatch({
              type: "SET_FORM_VALUES",
              payload: { joinedAt: Number(e.target.value) },
            })
          }
        />
        {formErrors.joinedAt && (
          <p className="text-sm font-medium text-destructive">{formErrors.joinedAt}</p>
        )}
      </div>
      <div className="space-y-2">
        <Label htmlFor="getGradeAt">級段位取得日</Label>
        <DatePicker
          date={formValues.getGradeAt ? new Date(formValues.getGradeAt) : undefined}
          onSelect={date =>
            dispatch({
              type: "SET_FORM_VALUES",
              payload: { getGradeAt: date ? date.toISOString().split("T")[0] : "" },
            })
          }
          placeholder="級段位取得日を選択"
        />
        {formErrors.getGradeAt && (
          <p className="text-sm font-medium text-destructive">{formErrors.getGradeAt}</p>
        )}
      </div>

      <div className="flex items-center gap-3 mt-4">
        <Checkbox
          id="legalAccepted"
          name="legalAccepted"
          required
          checked={formValues.legalAccepted}
          onCheckedChange={checked =>
            dispatch({
              type: "SET_FORM_VALUES",
              payload: { legalAccepted: !!checked },
            })
          }
        />
        <Label
          htmlFor="legalAccepted"
          className={style.label.required({
            class: "text-sm font-normal text-gray-898 dark:text-gray-300",
          })}
        >
          <Link
            to="https://omu-aikido.com/terms-of-service/"
            target="_blank"
            rel="noopener noreferrer"
            className="text-blue-600 hover:text-blue-800 dark:text-blue-400 dark:hover:text-blue-300 underline"
          >
            利用規約
          </Link>
          および
          <Link
            to="https://omu-aikido.com/privacy-policy/"
            target="_blank"
            rel="noopener noreferrer"
            className="text-blue-600 hover:text-blue-800 dark:text-blue-400 dark:hover:text-blue-300 underline"
          >
            プライバシーポリシー
          </Link>
          に同意します
        </Label>
      </div>
      {formErrors.legalAccepted && (
        <p className="text-sm font-medium text-destructive">{formErrors.legalAccepted}</p>
      )}

      <div className="flex gap-2">
        <Button
          type="button"
          variant="secondary"
          onClick={prevStep}
          className="flex-1"
          data-testid="sign-up-button-back-profile"
        >
          戻る
        </Button>

        <Button
          type="submit"
          className="flex-1"
          disabled={!canSubmit}
          data-testid="sign-up-button-submit"
        >
          {(fetcher.state !== "idle" || isSignUpCreated) && (
            <div className="animate-spin w-4 h-4 border-2 border-white border-t-transparent rounded-full mr-2" />
          )}
          {fetcher.state !== "idle" || isSignUpCreated ? "処理中..." : "アカウントを作成"}
        </Button>
      </div>
    </div>
  )
}
