// src/components/signup/SignUpStepPersonal.vue
<template>
  <div class="space-y-4">
    <div class="grid grid-cols-2 gap-4">
      <div class="space-y-2">
        <label for="lastName" class="text-sm font-medium text-neutral-700 dark:text-neutral-300">姓</label>
        <input
          id="lastName"
          name="lastName"
          type="text"
          :value="formValues.lastName"
          @input="
            onUpdate('lastName', ($event.target as HTMLInputElement).value)
          "
          required
          placeholder="山田"
          :disabled="isSignUpCreated"
          class="w-full rounded-md border border-neutral-300 dark:border-neutral-700 bg-white dark:bg-neutral-900 px-3 py-2 text-sm placeholder-neutral-400 focus:outline-none focus:ring-2 focus:ring-indigo-500 dark:text-neutral-100 disabled:opacity-50 disabled:cursor-not-allowed" />
        <p v-if="formErrors.lastName" class="text-sm text-red-600 dark:text-red-400">
          {{ formErrors.lastName }}
        </p>
      </div>
      <div class="space-y-2">
        <label for="firstName" class="text-sm font-medium text-neutral-700 dark:text-neutral-300">名</label>
        <input
          id="firstName"
          name="firstName"
          type="text"
          :value="formValues.firstName"
          @input="
            onUpdate('firstName', ($event.target as HTMLInputElement).value)
          "
          required
          placeholder="太郎"
          :disabled="isSignUpCreated"
          class="w-full rounded-md border border-neutral-300 dark:border-neutral-700 bg-white dark:bg-neutral-900 px-3 py-2 text-sm placeholder-neutral-400 focus:outline-none focus:ring-2 focus:ring-indigo-500 dark:text-neutral-100 disabled:opacity-50 disabled:cursor-not-allowed" />
        <p v-if="formErrors.firstName" class="text-sm text-red-600 dark:text-red-400">
          {{ formErrors.firstName }}
        </p>
      </div>
    </div>
    <div class="space-y-2">
      <label for="username" class="text-sm font-medium text-neutral-700 dark:text-neutral-300"
        >ユーザー名 (任意・6文字以上)</label
      >
      <input
        id="username"
        name="username"
        type="text"
        autocomplete="username"
        :value="formValues.username"
        @input="onUpdate('username', ($event.target as HTMLInputElement).value)"
        placeholder="aikido_taro"
        :disabled="isSignUpCreated"
        class="w-full rounded-md border border-neutral-300 dark:border-neutral-700 bg-white dark:bg-neutral-900 px-3 py-2 text-sm placeholder-neutral-400 focus:outline-none focus:ring-2 focus:ring-indigo-500 dark:text-neutral-100 disabled:opacity-50 disabled:cursor-not-allowed" />
      <p v-if="formErrors.username" class="text-sm text-red-600 dark:text-red-400">
        {{ formErrors.username }}
      </p>
    </div>
    <div class="flex justify-between pt-2">
      <button
        type="button"
        @click="prevStep"
        :disabled="isSignUpCreated"
        class="rounded-md border border-neutral-300 dark:border-neutral-600 px-4 py-2 text-sm font-medium text-neutral-700 dark:text-neutral-300 hover:bg-neutral-50 dark:hover:bg-neutral-800 focus:outline-none focus:ring-2 focus:ring-indigo-500 disabled:opacity-50 disabled:cursor-not-allowed">
        戻る
      </button>
      <button
        type="button"
        @click="handleNext"
        :disabled="isSignUpCreated"
        class="rounded-md bg-indigo-600 px-4 py-2 text-sm font-medium text-white hover:bg-indigo-700 focus:outline-none focus:ring-2 focus:ring-indigo-500 disabled:opacity-50 disabled:cursor-not-allowed">
        次へ
      </button>
    </div>
  </div>
</template>

<script setup lang="ts">
import type { SignUpFormData, FormErrors } from "@/src/composable/useSignUpForm"

const props = defineProps<{
  formValues: Partial<SignUpFormData>
  formErrors: Partial<FormErrors>
  isSignUpCreated: boolean
  handleNext: () => void
  prevStep: () => void
}>()

const emit = defineEmits<{
  (e: "update:formValue", key: keyof SignUpFormData, value: any): void
}>()

const onUpdate = (key: keyof SignUpFormData, value: any) => {
  emit("update:formValue", key, value)
}
</script>

// app/components/component/sign-up/SignUpStepPersonal.tsx
import type { FetcherWithComponents } from "react-router"

import { Button } from "~/components/ui/button"
import { Input } from "~/components/ui/input"
import { Label } from "~/components/ui/label"
import type {
  ClientActionReturn,
  FormAction,
  LocalFormState,
} from "~/hooks/useSignUpForm"
import { style } from "~/styles/component"

type SignUpStepPersonalProps = {
  formValues: LocalFormState
  formErrors: Record<string, string>
  dispatch: React.Dispatch<FormAction>
  fetcher: FetcherWithComponents<ClientActionReturn>
  isSignUpCreated: boolean
  handleNext: (e?: React.FormEvent) => void
  prevStep: () => void
}

export function SignUpStepPersonal({
  formValues,
  formErrors,
  dispatch,
  fetcher,
  isSignUpCreated,
  handleNext,
  prevStep,
}: SignUpStepPersonalProps) {
  return (
    <div className="space-y-4">
      <h2 className="text-lg font-semibold">個人情報</h2>
      <div className="space-y-2">
        <Label htmlFor="lastName" className={style.label.required()}>
          姓
        </Label>
        <Input
          id="lastName"
          name="lastName"
          type="text"
          autoComplete="family-name"
          required
          value={formValues.lastName}
          onChange={e =>
            dispatch({ type: "SET_FORM_VALUES", payload: { lastName: e.target.value } })
          }
        />
        {formErrors.lastName && (
          <p className="text-sm font-medium text-destructive">{formErrors.lastName}</p>
        )}
      </div>
      <div className="space-y-2">
        <Label htmlFor="firstName" className={style.label.required()}>
          名
        </Label>
        <Input
          id="firstName"
          name="firstName"
          type="text"
          autoComplete="given-name"
          required
          value={formValues.firstName}
          onChange={e =>
            dispatch({ type: "SET_FORM_VALUES", payload: { firstName: e.target.value } })
          }
        />
        {formErrors.firstName && (
          <p className="text-sm font-medium text-destructive">{formErrors.firstName}</p>
        )}
      </div>
      <div className="space-y-2">
        <Label htmlFor="username">ユーザー名</Label>
        <Input
          id="username"
          name="username"
          type="text"
          autoComplete="username"
          value={formValues.username}
          onChange={e =>
            dispatch({ type: "SET_FORM_VALUES", payload: { username: e.target.value } })
          }
        />
        {formErrors.username && (
          <p className="text-sm font-medium text-destructive">{formErrors.username}</p>
        )}
      </div>
      <div className="flex gap-2">
        <Button
          type="button"
          variant="secondary"
          onClick={prevStep}
          className="flex-1"
          data-testid="sign-up-button-back-personal"
        >
          戻る
        </Button>
        <Button
          type="button"
          onClick={handleNext}
          className="flex-1"
          disabled={fetcher.state !== "idle" || isSignUpCreated}
          data-testid="sign-up-button-next-personal"
        >
          {(fetcher.state !== "idle" || isSignUpCreated) && (
            <div className="mr-2 h-4 w-4 animate-spin rounded-full border-2 border-white border-t-transparent" />
          )}
          次へ
        </Button>
      </div>
    </div>
  )
}
